### ISSUE TITLE
The process data for PICL

### ISSUE THREAD

**Issue by DRSY** [t1101675/PICL#1]
Hi,

Thanks for the good work. Any plan to share the process data for ICL model training?

**Comment by t1101675** [comment]
Hi, thank you for your attention to our work. The pre-training data is too large to upload to google drive (~50G). We are still thinking about ways to share the data. 

You can try processing the data from the plain texts with our scripts.

**Comment by DRSY** [comment]
I have tried using the scripts in the repo and I encountered some issues. For example, in the file retrieval.py, line 358, it seems that there isn't such a file called "processed_0" after running all scripts as in README. Anything I need to modify to make it run successfully?

**Comment by t1101675** [comment]
It seemed to be something wrong when we modified the code to do extra experiments. We have updated the code and tested the whole data process pipeline. You can try this new code.
