### ISSUE TITLE
About Pre-training data

### ISSUE THREAD

**Issue by Frankey419** [t1101675/PICL#3]
In the pre-training phase, the original input text of the model is concatenated with k demonstrations. Does each demonstration have the task label? For example, the sentiment analysis task. If there are labels, how to get the labels from the general corpus?

**Comment by t1101675** [comment]
The demonstration does not have the task label. We assume the task label is intrinsically contained in the retrieved paragraph (i.e., each demonstration). For example, for the sentence: "Knowing that Argentina won the World Cup, he was excited to tears." doing the language modeling on the sentence performs the sentiment analysis task.
