### ISSUE TITLE
关于loss mask的设置

### ISSUE THREAD

**Issue by Thedatababbler** [t1101675/PICL#8]
您好，
我在运行您的pipeline的时候遇到了一些问题。但是我现在比较着急想知道您在训练的时候loss mask是怎么设置的。比如说现在输入的prompt含有两个example如下：<icl_example1><icl_example2><train_question><train_answer>。请问在训练阶段是否是将train_question及前面的两个example里面的token的loss全部设置为不训练，只计算生成train_answer里面的token的损失呢？不好意思，因为您在datasetr这块没有太多的comment，所以没有看太懂不得不来问您。希望您能解答，感谢。

**Comment by t1101675** [comment]
训练的时候会计算所有 token 得损失

**Comment by Thedatababbler** [comment]
可以请问一下为什么要计算所有token的损失吗？我看一下其它的论文里面比如MetaICL好像文中写的是只计算后面的答案的loss。我的理解也是这样，前面的example都是例子，后面才是需要训练的答案？全部训练效果会更好吗？

**Comment by t1101675** [comment]
这一点在 paper Section 2.3 说明了，在比较长的序列上算 loss 有助于保持模型的基础能力

**Comment by Thedatababbler** [comment]
十分感谢您的及时回复，抱歉之前没有注意到这个细节。那我现在加入要在您训练好的模型上来进行微调，我是否可以仅仅训练label的prediction任务呢？

**Comment by t1101675** [comment]
微调的话是可以的

**Comment by Thedatababbler** [comment]
好的 谢谢
