### ISSUE TITLE
关于作者开源的retriever

### ISSUE THREAD

**Issue by shs910** [t1101675/PICL#9]
请问作者开源的retriever在获取representation时是按照论文中所说对token的表征进行mean吗？
因为注意到，作者retriever.py代码中，inference函数内是直接拿的RobertaModel的outputs[1]，对应的是CLS。
谢谢

**Comment by t1101675** [comment]
您好，感谢指出问题！
我们检查了一下，开源的 retriever 确实是直接拿 CLS 作为句子的 representation。对 token 表征进行 mean 的应该是 SentenceRoBERTa 的 baseline。论文中的描述不准确，我们近期会进行修改。
